# Generated by Django 2.2.19 on 2022-04-06 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220406_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='adress',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='group',
            new_name='title',
        ),
    ]
